### ISSUE TITLE
Labels written multiple times

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/wrestling#18]
While investigating the animations (https://github.com/cyberbotics/webots/pull/5754), I remarked that for the animations of the competition some labels are written twice in the animation file.

For example in: https://raw.githubusercontent.com/cyberbotics/wrestling/main/storage/wb_animation_585201575/animation.json, the `KO` is written twice.

It doesn't seem to be the case with other animations (I tried with the `devices/worlds/supervisor.wbt`).

**Comment by omichel** [comment]
Yes, however, I believe we should fix this in Webots rather than in this specific simulation.
I believe that if a supervisor tries to modify a label by sending exactly the same values (color, position, text, font, etc.). Then, Webots should ignore this request and thus it won't be saved in the animation.

**Comment by BenjaminDeleze** [comment]
I fixed that in webots. However I still think that it should also be fixed in the controller of the wrestling as before the fix some labels were written 4 times which is not a good practice.
